// Stage 13 LVI mesh - autogenerated by runner.py
SetFactory("OpenCASCADE");
// All units mm; runner converts to m on .rad export.

cl_fine    = 1.0;
cl_medium  = 2.0;
cl_coarse  = 4.0;

// Laminate base rectangle (z=0) with concentric impact-zone subrectangle.
Point(1) = {-75.0, -50.0, 0, cl_coarse};
Point(2) = { 75.0, -50.0, 0, cl_coarse};
Point(3) = { 75.0,  50.0, 0, cl_coarse};
Point(4) = {-75.0,  50.0, 0, cl_coarse};

Line(1) = {1, 2}; Line(2) = {2, 3};
Line(3) = {3, 4}; Line(4) = {4, 1};
Line Loop(1) = {1, 2, 3, 4};

Point(5) = {-15.0, -15.0, 0, cl_fine};
Point(6) = { 15.0, -15.0, 0, cl_fine};
Point(7) = { 15.0,  15.0, 0, cl_fine};
Point(8) = {-15.0,  15.0, 0, cl_fine};
Line(5) = {5, 6}; Line(6) = {6, 7};
Line(7) = {7, 8}; Line(8) = {8, 5};
Line Loop(2) = {5, 6, 7, 8};

Plane Surface(1) = {1, 2};   // outer ring with hole = inner zone
Plane Surface(2) = {2};      // refined inner zone

// Extrude through-thickness with one HEXA8 layer per ply.
out_outer[] = Extrude {0, 0, 4.0} {
    Surface{1}; Layers{ 24 }; Recombine;
};
out_inner[] = Extrude {0, 0, 4.0} {
    Surface{2}; Layers{ 24 }; Recombine;
};

// Hemispherical impactor (rigid; surface only for contact).
impactor_centre_z = 12.05;
SetFactory("OpenCASCADE");
Sphere(100) = {0, 0, impactor_centre_z, 8.0, -Pi/2, 0};
// The hemisphere's flat face becomes the upper boundary of the rigid
// body; only the lower hemisphere contacts the laminate.

// Physical groups for OpenRadioss /SUBSET / /GRBRIC tagging.
Physical Volume("LAMINATE_INNER") = {out_inner[1]};
Physical Volume("LAMINATE_OUTER") = {out_outer[1]};
Physical Volume("IMPACTOR")       = {100};
Physical Surface("LAM_TOP")       = {out_inner[0], out_outer[0]};
Physical Surface("LAM_BOTTOM")    = {1, 2};

Mesh.RecombineAll = 1;
Mesh.Algorithm    = 8;     // Frontal-Delaunay for quad
Mesh.Algorithm3D  = 1;     // Delaunay
Mesh.ElementOrder = 1;     // linear, HEXA8
